### ISSUE TITLE
.vimrc includes a dead link to the pathogen.vim link

### ISSUE THREAD

**Issue by christopherbridenstine** [mbrochh/vim-as-a-python-ide#2]
The .vimrc file includes a dead link to the pathegen.vim script from tpope.  It looks as though github has changed the entry url for accessing raw files from repositories through http.

I went ahead and forked the project and committed the change which can be found here:
https://github.com/christopherbridenstine/vim-as-a-python-ide/commit/b0674d1efcdc2ffbfbc5db640fc30cc2fa485e08

I'm not sure if you intended to link to the HEAD branch version of the file, but my change included a link to the master branch version of tpope's script.  The HEAD branch version can still be found under the new access url.

**Comment by mbrochh** [comment]
Thanks for reporting this. I have incorporated your change into my repo as well.

**Comment by christopherbridenstine** [comment]
No problem man.  I'm attempting to streamline my vim configurations across
machines and your guide helped a ton.  I've been having to make minor
changes over time and I thought I would report this one.

On Sun, Jun 22, 2014 at 11:52 AM, Martin Brochhaus <notifications@github.com

> wrote:
> 
> Thanks for reporting this. I have incorporated your change into my repo as
> well.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mbrochh/vim-as-a-python-ide/issues/2#issuecomment-46784573
> .

## 

Christopher Bridenstine
Christopher.Bridenstine@gmail.com | +1-415-617-5214
