### ISSUE TITLE
error with jedi-vim in debian

### ISSUE THREAD

**Issue by adrian-gluu** [mbrochh/vim-as-a-python-ide#5]
Error: jedi-vim failed to initialize Python: jedi-vim requires Vim with support for Python 2 or 3. (in fu
nction jedi#init_python..<SNR>31_init_python, line 40)

**Comment by mbrochh** [comment]
Did you see the slides and watch the talk? You need to compile Vim yourself
with Python support.

Alternatively you can install neovim, it's fully compatible and has Python
support always enabled.

**Comment by adrian-gluu** [comment]
just got this fixed installing the pkg vim-python-jedi
