### ISSUE TITLE
inoremap <C-n> :nohl<CR>

### ISSUE THREAD

**Issue by doubleloop** [mbrochh/vim-as-a-python-ide#6]
I just watched your youtube video, found out this repo and am playing around with the settings, still I found the setting is strange:

``` vim
inoremap <C-n> :nohl<CR>
```

Am i right that all it does is making ctrl+n in insert mode pasting the ":nohl\n"?

**Comment by mbrochh** [comment]
I can't quite remember, I never really used that shortcut. I believe the point is, when you search something, then the matches will be highlighted, and when you want to get rid of the highlights, you can type `:nohl`, so in my current `.vimrc` this binding is actually `noremap <Leader>h :nohl<CR>`, so when I press that key-combo, the highlights will disappear.
